# Automatically label PRs based on changed files
# Format for actions/labeler@v5

documentation:
  - changed-files:
      - any-glob-to-any-file:
          - '**/*.md'
          - 'docs/**/*'

dependencies:
  - changed-files:
      - any-glob-to-any-file:
          - 'package.json'
          - 'package-lock.json'
          - 'npm-shrinkwrap.json'

ci/cd:
  - changed-files:
      - any-glob-to-any-file:
          - '.github/**/*'
          - 'Dockerfile'
          - 'docker-compose.yml'
          - '.dockerignore'

tests:
  - changed-files:
      - any-glob-to-any-file:
          - '**/*.spec.ts'
          - '**/*.test.ts'
          - 'test/**/*'

source:
  - changed-files:
      - any-glob-to-any-file:
          - 'src/**/*'

config:
  - changed-files:
      - any-glob-to-any-file:
          - '*.config.*'
          - '.*rc'
          - '.editorconfig'
          - 'tsconfig*.json'
