import { MigrationInterface, QueryRunner } from 'typeorm';

/**
 * AddPaymentTermLinkToPayments
 *
 * Repurposes the existing `payments` table to act as the receipts ledger
 * (per Project Finance plan §2.2 — table name retained for migration safety).
 *
 *   1. Adds nullable `payment_term_id` FK to `project_payment_terms`
 *      (ON DELETE RESTRICT — terms with linked receipts cannot be deleted).
 *   2. Replaces the global UNIQUE constraint on `payment_number` with a
 *      composite (organization_id, payment_number) partial-unique on
 *      not-soft-deleted rows. This prevents cross-org collisions and is
 *      required for FY-prefixed sequence numbers (RCP-{FY}-{6digits}).
 *
 * NOTE: Reformatting of legacy `payment_number` values from the old
 * `PAY-{YYYY}-{NNN}` shape to the new `RCP-{FY}-{6digits}` shape is handled
 * by the receipts module's runtime number generator (which only assigns the
 * new format on new inserts). Existing rows keep their historical numbers —
 * they remain unique within their organization which is all the new
 * constraint requires.
 */
export class AddPaymentTermLinkToPayments1830000000001 implements MigrationInterface {
  name = 'AddPaymentTermLinkToPayments1830000000001';

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`
      ALTER TABLE payments
        ADD COLUMN IF NOT EXISTS payment_term_id UUID;
    `);

    await queryRunner.query(`
      DO $$
      BEGIN
        IF NOT EXISTS (
          SELECT 1 FROM pg_constraint
          WHERE conname = 'fk_payments_payment_term'
        ) THEN
          ALTER TABLE payments
            ADD CONSTRAINT fk_payments_payment_term
            FOREIGN KEY (payment_term_id)
            REFERENCES project_payment_terms(id)
            ON DELETE RESTRICT;
        END IF;
      END $$;
    `);

    await queryRunner.query(`
      CREATE INDEX IF NOT EXISTS idx_payments_payment_term
        ON payments(payment_term_id)
        WHERE deleted_at IS NULL AND payment_term_id IS NOT NULL;
    `);

    // Drop the legacy global unique on payment_number (autogenerated name
    // varies across environments — discover it dynamically).
    await queryRunner.query(`
      DO $$
      DECLARE
        cons_name TEXT;
      BEGIN
        SELECT conname INTO cons_name
        FROM pg_constraint
        WHERE conrelid = 'payments'::regclass
          AND contype = 'u'
          AND pg_get_constraintdef(oid) ILIKE '%(payment_number)%'
        LIMIT 1;

        IF cons_name IS NOT NULL THEN
          EXECUTE format('ALTER TABLE payments DROP CONSTRAINT %I', cons_name);
        END IF;
      END $$;
    `);

    await queryRunner.query(`
      CREATE UNIQUE INDEX IF NOT EXISTS uq_payments_org_number_active
        ON payments(organization_id, payment_number)
        WHERE deleted_at IS NULL;
    `);
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`DROP INDEX IF EXISTS uq_payments_org_number_active;`);

    // Restore a non-unique index so existing queries still perform; we do not
    // re-add the legacy global unique because callers may already have
    // FY-prefixed numbers that collide across orgs.
    await queryRunner.query(`
      CREATE INDEX IF NOT EXISTS idx_payments_payment_number
        ON payments(payment_number);
    `);

    await queryRunner.query(`DROP INDEX IF EXISTS idx_payments_payment_term;`);

    await queryRunner.query(`
      DO $$
      BEGIN
        IF EXISTS (
          SELECT 1 FROM pg_constraint WHERE conname = 'fk_payments_payment_term'
        ) THEN
          ALTER TABLE payments DROP CONSTRAINT fk_payments_payment_term;
        END IF;
      END $$;
    `);

    await queryRunner.query(`
      ALTER TABLE payments DROP COLUMN IF EXISTS payment_term_id;
    `);
  }
}
