import { ApiProperty, ApiPropertyOptional } from '@nestjs/swagger';
import { ProjectType, QuoteSnapshot, SystemType } from '@tejas96/shared/types';
import { Type } from 'class-transformer';
import {
  IsArray,
  IsBoolean,
  IsDateString,
  IsEnum,
  IsInt,
  IsNotEmpty,
  IsNumber,
  IsObject,
  IsOptional,
  IsString,
  IsUUID,
  Min,
  ValidateNested,
} from 'class-validator';

import { PaymentMilestoneDto } from '../versions/payment-milestone.dto';

/**
 * DTO for creating a new quote
 */
export class CreateQuoteDto {
  // ==================== Relations ====================
  @ApiProperty({
    example: '123e4567-e89b-12d3-a456-426614174000',
    description: 'Customer ID',
  })
  @IsUUID()
  @IsNotEmpty()
  customerId!: string;

  @ApiPropertyOptional({
    example: '123e4567-e89b-12d3-a456-426614174000',
    description: 'Sales person ID',
  })
  @IsUUID()
  @IsOptional()
  salesPersonId?: string;

  @ApiPropertyOptional({
    example: '123e4567-e89b-12d3-a456-426614174000',
    description: 'Reseller ID (if quote is generated by reseller)',
  })
  @IsUUID()
  @IsOptional()
  resellerId?: string;

  @ApiProperty({
    example: '123e4567-e89b-12d3-a456-426614174000',
    description: 'Property ID for installation site',
  })
  @IsUUID()
  @IsNotEmpty()
  propertyId!: string;

  // ==================== Quote Info ====================
  @ApiPropertyOptional({
    example: '2025-01-15',
    description: 'Quote date (defaults to today)',
  })
  @IsDateString()
  @IsOptional()
  quoteDate?: string;

  @ApiProperty({
    example: '2025-02-15',
    description: 'Valid until date (quote expiry)',
  })
  @IsDateString()
  @IsNotEmpty()
  validUntil!: string;

  // ==================== System Details ====================
  @ApiProperty({
    enum: Object.values(SystemType),
    enumName: 'SystemType',
    example: SystemType.ON_GRID,
    description: 'Solar system type',
  })
  @IsEnum(SystemType)
  @IsNotEmpty()
  systemType!: SystemType;

  @ApiProperty({
    example: 5500,
    description: 'Total panel wattage in Wp (canonical system size source)',
  })
  @IsInt()
  @Min(0)
  @IsNotEmpty()
  totalWattageWp!: number;

  // ==================== Project Type ====================
  @ApiProperty({
    enum: Object.values(ProjectType),
    enumName: 'ProjectType',
    example: ProjectType.RESIDENTIAL,
    description: 'Project type',
  })
  @IsEnum(ProjectType)
  @IsNotEmpty()
  projectType!: ProjectType;

  // ==================== Pricing ====================
  @ApiPropertyOptional({
    example: 0,
    description: 'Discount amount in INR',
  })
  @IsNumber({ maxDecimalPlaces: 2 })
  @Min(0)
  @IsOptional()
  discountAmount?: number;

  @ApiPropertyOptional({
    example: 327180,
    description: 'Final price after GST and discount',
  })
  @IsNumber()
  @Min(0)
  @IsOptional()
  finalPrice?: number;

  @ApiPropertyOptional({
    example: 249180,
    description: 'Effective price after subsidy (what customer pays)',
  })
  @IsNumber()
  @Min(0)
  @IsOptional()
  effectivePrice?: number;

  // ==================== Quote Snapshot ====================
  @ApiPropertyOptional({
    description: 'Complete quote snapshot (inputs + calculation + pricing)',
  })
  @IsOptional()
  @IsObject()
  quoteSnapshot?: QuoteSnapshot;

  // ==================== Loan Financing ====================
  @ApiPropertyOptional({
    example: false,
    description:
      'Customer wants loan financing. Payment milestones are 10%/85%/5% for all projects.',
  })
  @IsBoolean()
  @IsOptional()
  wantsLoan?: boolean;

  // ==================== Notes ====================
  @ApiPropertyOptional({
    example: 'High priority customer, offer best pricing',
    description: 'Internal notes (not visible to customer)',
  })
  @IsString()
  @IsOptional()
  internalNotes?: string;

  @ApiPropertyOptional({
    example: 'Installation to be completed before summer',
    description: 'Notes visible to customer',
  })
  @IsString()
  @IsOptional()
  customerNotes?: string;

  // ==================== Version Details ====================
  @ApiPropertyOptional({
    example: 4,
    description: 'Project completion weeks (default: 4)',
  })
  @IsInt()
  @Min(1)
  @IsOptional()
  projectCompletionWeeks?: number;

  @ApiPropertyOptional({
    type: [PaymentMilestoneDto],
    description: 'Payment milestones (auto-generated if not provided)',
  })
  @IsArray()
  @ValidateNested({ each: true })
  @Type(() => PaymentMilestoneDto)
  @IsOptional()
  paymentMilestones?: PaymentMilestoneDto[];
}
